census-instrumentation/opencensus-node

- AUTHORS
- packages/opencensus-core/AUTHORS
This PR updates the AUTHORS file to match Google's guidelines for Open Source projects.
> chore: update AUTHORS

- packages/opencensus-core/src/internal/cls.ts
- packages/opencensus-core/src/trace/model/tracer.ts
- packages/opencensus-core/test/test-tracer.ts
Fix for the issue found on PR/6
> fix: nodejs 6 async_hook issue

- packages/opencensus-propagation-stackdriver/package-lock.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-stackdriver/src/index.ts
- packages/opencensus-propagation-stackdriver/src/v1.ts
- packages/opencensus-propagation-stackdriver/test/test-v1.ts
- packages/opencensus-propagation-stackdriver/tsconfig.json
Introduces a package for Stackdriver propagation. Right now only v1 format is implemented.
TODO:
> Opencensus propagation stackdriver

- packages/opencensus-propagation-stackdriver/package.json
[Release Notes](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-36593abe846209c55474)
> chore(propagation-stackdriver): 0.0.1-pre release proposal

- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-stackdriver/src/stackdriver.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver.ts
- packages/opencensus-exporter-stackdriver/tsconfig.json
Adds GTS and fixes GTS highlighted issues. Addresses Issue #26.
> refactor: stackdriver tsconfig - use gts

- packages/opencensus-core/src/common/console-logger.ts
- packages/opencensus-core/test/test-console-logger.ts
- packages/opencensus-core/test/test-root-span.ts
- packages/opencensus-core/test/test-span.ts
- packages/opencensus-core/test/test-tracer.ts
- packages/opencensus-core/tsconfig.json
Fix tsconfig.ts form core package.
> refactor: tsconfig.ts from core package

- packages/opencensus-instrumentation-http/src/http.ts
- packages/opencensus-instrumentation-http/test/test-http.ts
- packages/opencensus-instrumentation-https/test/test-https.ts
This PR address instrumentation-http TODOs
> refactor: address instrumentation-http TODOs

- packages/opencensus-exporter-jaeger/AUTHORS
- packages/opencensus-exporter-jaeger/LICENSE
- packages/opencensus-exporter-jaeger/README.md
- packages/opencensus-exporter-jaeger/package-lock.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-jaeger/src/index.ts
- packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
- packages/opencensus-exporter-jaeger/src/jaeger.ts
- packages/opencensus-exporter-jaeger/test/test-jaeger.ts
- packages/opencensus-exporter-jaeger/tsconfig.json
This PR adds Jaeger exporter package to opencensus-node. Unit tests are included.
> feat: add jaeger exporter to opencensus-node

- .circleci/config.yml
- packages/opencensus-instrumentation-mongodb/.npmignore
- packages/opencensus-instrumentation-mongodb/AUTHORS
- packages/opencensus-instrumentation-mongodb/LICENSE
- packages/opencensus-instrumentation-mongodb/README.md
- packages/opencensus-instrumentation-mongodb/package-lock.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-mongodb/src/index.ts
- packages/opencensus-instrumentation-mongodb/src/mongodb.ts
- packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
- packages/opencensus-instrumentation-mongodb/tsconfig.json
This PR adds MongoDB instrumentation package to opencensus-node. Unit tests are included.
> feat: add package instrumentation-mongodb to opencensus-node

- README.md
- examples/automatic_tracing/README.md
- examples/automatic_tracing/instana.js
- examples/automatic_tracing/stackdriver.js
- examples/automatic_tracing/zipkin.js
- packages/opencensus-exporter-instana/.npmignore
- packages/opencensus-exporter-instana/AUTHORS
- packages/opencensus-exporter-instana/LICENSE
- packages/opencensus-exporter-instana/README.md
- packages/opencensus-exporter-instana/package-lock.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-instana/src/index.ts
- packages/opencensus-exporter-instana/src/instana.ts
- packages/opencensus-exporter-instana/test/test-instana.ts
- packages/opencensus-exporter-instana/tsconfig.json
A fully functional trace exporter for [Instana](https://www.instana.com/). Basically a copy of the Zipkin/Stackdriver exporters with some Instana specific adaptations.
> feat: add package exporter-instana to opencensus-node

- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-all/src/index.js
- packages/opencensus-instrumentation-grpc/.npmignore
- packages/opencensus-instrumentation-grpc/AUTHORS
- packages/opencensus-instrumentation-grpc/LICENSE
- packages/opencensus-instrumentation-grpc/README.md
- packages/opencensus-instrumentation-grpc/package-lock.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-grpc/src/grpc.ts
- packages/opencensus-instrumentation-grpc/src/index.ts
- packages/opencensus-instrumentation-grpc/test/fixtures/grpc-instrumentation-test.proto
- packages/opencensus-instrumentation-grpc/test/test-grpc.ts
- packages/opencensus-instrumentation-grpc/tsconfig.json
This PR adds instrumentation-grpc package to opencensus-node. Unit tests are included.
> feat: add instrumentation-grpc package to opencensus-node

- packages/opencensus-core/src/trace/model/root-span.ts
- packages/opencensus-core/src/trace/model/span-base.ts
- packages/opencensus-core/src/trace/model/types.ts
- packages/opencensus-core/test/test-tracer.ts
- packages/opencensus-exporter-instana/src/instana.ts
- packages/opencensus-instrumentation-grpc/src/grpc.ts
- packages/opencensus-instrumentation-grpc/test/test-grpc.ts
- packages/opencensus-instrumentation-http/src/http.ts
- packages/opencensus-instrumentation-http2/src/http2.ts
- packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
The aim of this PR is to rename property span.type to span.kind
> refactor: rename span.type to span.kind

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-stackdriver/package.json
[Release Notes](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-d3ac386bf8a2ef9d159f)
> chore(multiple): 0.0.2 release proposal

- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts
- packages/opencensus-nodejs/test/test-plugin-loader.ts
If tests pass, this should allow #65 to land.
> fix: add states to plugin loader mechanism

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
[Release Notes](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-33851390fb4b58408668)
>  chore(multiple): 0.0.3 release proposal

- packages/opencensus-core/package.json
- packages/opencensus-core/src/stats/recorder.ts
- packages/opencensus-core/src/stats/types.ts
- packages/opencensus-core/src/stats/view.ts
- packages/opencensus-core/test/test-recorder.ts
- Add the `recorder` implementation
- Adds `recorder` tests
- Refactors code
- removes `bucketsBoundaries`
- changes `bucket.max` to `bucket.highBoundary`
- changes `bucket.min` to `bucket.lowBoundary`
> feat: add stats recorder implementation

- packages/opencensus-exporter-zipkin/README.md
Hopefully will help prevent demo update emergencies in the future
See https://github.com/census-instrumentation/opencensus-node/issues/102
> Clarifies the url is a url with an example

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
[Release Notes](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-5580f792368205a211b9)
> chore(multiple): 0.0.4 release proposal

- packages/opencensus-instrumentation-grpc/package.json
> chore(instrumentation-grpc): add prepare command and propose 0.0.5

- packages/opencensus-exporter-prometheus/README.md
> doc: correct prometheus exporter description in README

- packages/opencensus-instrumentation-grpc/src/grpc.ts
- packages/opencensus-instrumentation-http/src/http.ts
- packages/opencensus-instrumentation-https/src/https.ts
> Fix 'pacth' to 'patch'

- lerna.json
- package-lock.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-694f0bf9c9de02e39886
> chore(multiple): 0.0.6 release proposal

- packages/opencensus-core/src/stats/stats.ts
- packages/opencensus-core/src/stats/view.ts
- packages/opencensus-core/test/test-stats.ts
- packages/opencensus-core/test/test-view.ts
Issue https://github.com/census-instrumentation/opencensus-node/issues/172
> Drops negative bucket bounds and negative values in record API

- lerna.json
- package-lock.json
- package.json
- packages/opencensus-exporter-stackdriver/package-lock.json
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
[Issue 182](https://github.com/census-instrumentation/opencensus-node/issues/182)
> Disables broken test with newest gcloud

- CONTRIBUTING.md
[Issue 180](https://github.com/census-instrumentation/opencensus-node/issues/180)
> Adds contributing document

- packages/opencensus-core/src/stats/stats.ts
- packages/opencensus-core/test/test-stats.ts
Issue [206](https://github.com/census-instrumentation/opencensus-node/issues/206)
> Drops whole measurement list if some of value is negative

- CHANGELOG.md
- packages/opencensus-core/src/stats/recorder.ts
- packages/opencensus-core/src/stats/types.ts
- packages/opencensus-core/src/stats/view.ts
- packages/opencensus-core/test/test-recorder.ts
- packages/opencensus-core/test/test-view.ts
- packages/opencensus-exporter-zpages/templates/statsz-view-distribution.ejs
- packages/opencensus-exporter-zpages/test/test-zpages.ts
> Remove min/max from Distribution

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-7bad17fe5e1fb5d187af
> chore(multiple): 0.0.8 release proposal

- packages/opencensus-exporter-jaeger/README.md
> Add usage instructions

- CHANGELOG.md
- packages/opencensus-exporter-zipkin/README.md
- packages/opencensus-exporter-zipkin/src/zipkin.ts
- packages/opencensus-exporter-zipkin/test/test-zipkin.ts
>  exporter/Zipkin: Add missing fields (Annotation,Status,MessageEvent etc)

- packages/opencensus-core/src/trace/model/types.ts
- packages/opencensus-exporter-ocagent/src/adapters.ts
- packages/opencensus-exporter-ocagent/test/test-ocagent.ts
- packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
This PR is based on the discussion here: https://github.com/census-instrumentation/opencensus-website/pull/580.
> Update uncompressedSize and compressedSize for the exporters

- CHANGELOG.md
- packages/opencensus-propagation-binaryformat/.npmignore
- packages/opencensus-propagation-binaryformat/AUTHORS
- packages/opencensus-propagation-binaryformat/LICENSE
- packages/opencensus-propagation-binaryformat/README.md
- packages/opencensus-propagation-binaryformat/codecov.yml
- packages/opencensus-propagation-binaryformat/package-lock.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-binaryformat/src/binary-format.ts
- packages/opencensus-propagation-binaryformat/src/index.ts
- packages/opencensus-propagation-binaryformat/test/test-binary-format.ts
- packages/opencensus-propagation-binaryformat/tsconfig.json
See: https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md
Nothing is exported in `index.ts` yet because I want to implement ```BinaryFormat``` class after this PR.
> Add support for Binary propagation format 

- CHANGELOG.md
- packages/opencensus-exporter-zipkin/README.md
- packages/opencensus-exporter-zipkin/src/zipkin.ts
- packages/opencensus-exporter-zipkin/test/test-zipkin.ts
- packages/opencensus-exporter-zipkin/tsconfig.json
>  Exporter/Zipkin: Enforce strictNullChecks and noUnusedLocals

- package-lock.json
- packages/opencensus-instrumentation-grpc/package-lock.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-grpc/tsconfig.json
> Bump protobufjs to 6.x

- packages/opencensus-instrumentation-mongodb/src/mongodb.ts
- packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
- packages/opencensus-instrumentation-mongodb/tsconfig.json
> Enforce/strictNullChecks: MongoDB Plugin

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This will automatically add labels for new bug or feature report.
bug, triage me -> Bug Report
feature-request, triage me -> Feature Report
> Add default labels for ISSUE_TEMPLATE

- packages/opencensus-nodejs/src/trace/tracing.ts
- packages/opencensus-nodejs/test/test-tracing.ts
- packages/opencensus-nodejs/tsconfig.json
This is part of #348. 5 more packages to go, 17 is done so far.
> opencensus-nodejs: Enforce strictNullChecks

- packages/opencensus-core/package-lock.json
- packages/opencensus-exporter-instana/package-lock.json
- packages/opencensus-exporter-jaeger/package-lock.json
- packages/opencensus-exporter-ocagent/package-lock.json
- packages/opencensus-exporter-prometheus/package-lock.json
- packages/opencensus-exporter-stackdriver/package-lock.json
- packages/opencensus-exporter-zipkin/package-lock.json
- packages/opencensus-instrumentation-grpc/package-lock.json
- packages/opencensus-instrumentation-http/package-lock.json
- packages/opencensus-instrumentation-http2/package-lock.json
- packages/opencensus-instrumentation-https/package-lock.json
- packages/opencensus-instrumentation-ioredis/package-lock.json
- packages/opencensus-instrumentation-mongodb/package-lock.json
- packages/opencensus-instrumentation-redis/package-lock.json
- packages/opencensus-nodejs/package-lock.json
- packages/opencensus-propagation-b3/package-lock.json
- packages/opencensus-propagation-binaryformat/package-lock.json
- packages/opencensus-propagation-jaeger/package-lock.json
- packages/opencensus-propagation-stackdriver/package-lock.json
- packages/opencensus-propagation-tracecontext/package-lock.json
> Chore: sync package-lock

- packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/agent/common/v1/common.proto
- packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/agent/trace/v1/trace_service.proto
- packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/resource/v1/resource.proto
- packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/trace/v1/trace.proto
- packages/opencensus-exporter-ocagent/src/protos/opencensus/proto/trace/v1/trace_config.proto
> Regenerate ocagent proto files

- examples/gauge/derived-gauge-quickstart.js
- packages/opencensus-core/src/metrics/gauges/derived-gauge.ts
- packages/opencensus-core/test/test-derived-gauge.ts
> Derived Gauge: Add support for extracting value from a function

- package-lock.json
- update handlebar to avoid security vulnerability
(Breaks other PRs on Snyk integration)
> chore(package): update handlebar to avoid security vulnerability

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
[Release draft notes](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-5e9803fe5c075f82703f)
> chore(multiple): 0.0.12 release proposal

- packages/opencensus-core/src/trace/model/no-record/no-record-span.ts
- packages/opencensus-core/test/test-no-record-root-span.ts
- packages/opencensus-core/test/test-no-record-span.ts
- packages/opencensus-core/test/test-root-span.ts
- packages/opencensus-core/test/test-span.ts
> Fix: handle infinite loop caused by get traceState()

- packages/opencensus-exporter-ocagent/package-lock.json
- packages/opencensus-exporter-ocagent/package.json
this is essential for Node 12 ci job. Splitting the change from https://github.com/census-instrumentation/opencensus-node/pull/504 PR.
> Chore: update GRPC to 1.12.3

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-prometheus/src/prometheus-stats.ts
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
[Release notes, draft](https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-51a3a95ba2a6a1512e88)
> chore(multiple): 0.0.13 release proposal

- packages/opencensus-core/test/test-binary-serializer.ts
- packages/opencensus-core/test/test-derived-cumulative.ts
- packages/opencensus-core/test/test-derived-gauge.ts
- packages/opencensus-core/test/test-gauge.ts
- packages/opencensus-core/test/test-metric-producer-manager.ts
- packages/opencensus-core/test/test-resource.ts
- packages/opencensus-core/test/test-root-span.ts
- packages/opencensus-core/test/test-span.ts
- packages/opencensus-core/test/test-stats.ts
- packages/opencensus-core/test/test-text-format.ts
- packages/opencensus-core/test/test-variant-encoding.ts
- packages/opencensus-core/test/test-view.ts
- packages/opencensus-exporter-jaeger/test/test-jaeger.ts
- packages/opencensus-exporter-ocagent/test/test-ocagent.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
- packages/opencensus-exporter-zipkin/test/test-zipkin.ts
- packages/opencensus-exporter-zpages/test/test-zpages.ts
- packages/opencensus-instrumentation-grpc/test/test-grpc.ts
- packages/opencensus-nodejs-base/test/test-tracing.ts
- packages/opencensus-propagation-b3/test/test-b3-format.ts
- packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts
- packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts
- packages/opencensus-propagation-stackdriver/test/test-v1.ts
- packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts
- packages/opencensus-resource-util/test/test-detect-resource.ts
> Replace assert.deepEqual with assert.deepStrictEqual

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package-lock.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package-lock.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
Release notes, draft: https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-dc326e2d962c653f51b8
> chore(multiple): 0.0.14 release proposal

- examples/grpc/capitalize_client.js
- examples/grpc/capitalize_server.js
- examples/http/client.js
- examples/http/server.js
- packages/opencensus-instrumentation-grpc/src/grpc.ts
- packages/opencensus-instrumentation-http/src/http-stats.ts
- packages/opencensus-propagation-binaryformat/test/test-binary-format.ts
> Fix License header: replace gRPC:// with https://

- packages/opencensus-exporter-stackdriver/package-lock.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
- Update dependency google-auth-library to v4
- Update dependency googleapis to v40
> Update dependency google-auth-library and googleapis

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
Release notes, draft: https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-8ad524ebf10afef0af8f
> chore(multiple): 0.0.15 release proposal

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
Release draft: https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-7389f1a2df50bae972be
> chore(multiple): 0.0.17 release proposal

- packages/opencensus-instrumentation-http2/src/http2.ts
- packages/opencensus-instrumentation-http2/test/test-http2.ts
This PR fixes https://github.com/census-instrumentation/opencensus-node/issues/641.
> Fix the problem caused by multiple http2.connect calls

- packages/opencensus-core/src/tags/tag-map.ts
- packages/opencensus-core/test/test-tag-map.ts
> Fix: silently ignore the invalid keys and values

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package-lock.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
The draft release notes: https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-533c9a98d9667022b598
> chore(multiple): 0.0.18 release proposal

- packages/opencensus-exporter-stackdriver/test/nocks.ts
- packages/opencensus-resource-util/package-lock.json
- packages/opencensus-resource-util/package.json
- packages/opencensus-resource-util/test/test-detect-resource.ts
> chore: upgrade gcp-metadata to ^3.0.0

- .gitignore
- package-lock.json
- package.json
- packages/opencensus-core/tsconfig.json
> Add typedoc docs

- packages/opencensus-exporter-stackdriver/src/common-utils.ts
- packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
> Fix: fallback to global resource type when expected labels are missing

- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package-lock.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
Release draft notes => https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-5c759d8a05875b98f9a3
> chore(multiple): 0.0.19 release proposal

- packages/opencensus-core/src/trace/model/tracer-base.ts
- packages/opencensus-core/test/test-tracer-base.ts
> Fix CoreTracerBase not respecting propagated trace options

- CHANGELOG.md
- lerna.json
- packages/opencensus-core/package.json
- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-azure/package-lock.json
- packages/opencensus-exporter-azure/package.json
- packages/opencensus-exporter-instana/package.json
- packages/opencensus-exporter-jaeger/package.json
- packages/opencensus-exporter-object/package.json
- packages/opencensus-exporter-ocagent/package.json
- packages/opencensus-exporter-prometheus/package.json
- packages/opencensus-exporter-stackdriver/package.json
- packages/opencensus-exporter-zipkin/package.json
- packages/opencensus-exporter-zpages/package.json
- packages/opencensus-instrumentation-all/package.json
- packages/opencensus-instrumentation-grpc/package.json
- packages/opencensus-instrumentation-http/package.json
- packages/opencensus-instrumentation-http2/package.json
- packages/opencensus-instrumentation-https/package.json
- packages/opencensus-instrumentation-ioredis/package.json
- packages/opencensus-instrumentation-mongodb/package.json
- packages/opencensus-instrumentation-redis/package.json
- packages/opencensus-nodejs-base/package.json
- packages/opencensus-nodejs/package.json
- packages/opencensus-propagation-b3/package.json
- packages/opencensus-propagation-binaryformat/package.json
- packages/opencensus-propagation-jaeger/package.json
- packages/opencensus-propagation-stackdriver/package.json
- packages/opencensus-propagation-tracecontext/package.json
- packages/opencensus-resource-util/package.json
Release draft: https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-e6702074366df6408cc1
> chore:  0.0.22 release proposal

- .github/CODEOWNERS
A few PRs security updates and PRs need to be merged, but I don't have access to merge.
> Nominating myself (@aabmass) as codeowner

- packages/opencensus-exporter-zpages/package-lock.json
- packages/opencensus-exporter-zpages/package.json
Upgrade ejs (recreate of #884)
> upgrade ejs

- renovate.json
https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
> chore: enable renovate lockfile maintenance

- packages/opencensus-example-automatic-tracing/package.json
- packages/opencensus-exporter-azure/package.json
> chore: add repository field to azure package.json for wombot
