census-instrumentation/opencensus-node

packages/opencensus-core/package.json, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/test/test-console-exporter.ts
This was the last commit from PR/2 that was not merged to master.
=> refactor: fix some dependencies, file copyright  and typos

.circleci/config.yml, package.json, packages/opencensus-core/package.json
This PR starts running CI with CircleCI. We currently don't test Node 10 because of known issues related to ts-node (that should be fixed tomorrow, hopefully).
I've also removed the `build` command and changed references to it to `compile`. @fabiogomessilva does this seem alright to you?
=> chore: start testing on circleci

packages/opencensus-core/src/index-types.ts, packages/opencensus-core/src/trace/config/types.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/src/trace/propagation/types.ts
This PR adds the Propagation interface proposed by @ofrobots to Core. Also, a propagation property was also added to Config and Tracer.
=> feat: add propagation interface to core

packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/types.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-console-exporter.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-exporter-stackdriver/src/stackdriver.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-https/test/test-https.ts, packages/opencensus-nodejs/src/trace/tracing.ts
To address Zpages exporter features was necessary to add a new method 'onStartSpan' to OnEndSpanEventListener interface. Then this interface was renamed to SpanEventListener.
=> feat: add onStartSpan method to OnEndSpanEventListener interface and rename it to SpanEventListener

packages/opencensus-instrumentation-all/.npmignore, packages/opencensus-instrumentation-all/AUTHORS, packages/opencensus-instrumentation-all/LICENSE, packages/opencensus-instrumentation-all/package-lock.json, packages/opencensus-instrumentation-all/package.json, packages/opencensus-instrumentation-all/src/index.d.ts, packages/opencensus-instrumentation-all/src/index.js, packages/opencensus-nodejs/package.json, packages/opencensus-nodejs/src/trace/constants.ts
This PR adds package 'instrumentation-all' which has only dependencies to all default instrumentation packages. 
This package will be a dependency for package @opencensus/nodejs, and its main goal is to avoid the end user to add these dependencies to their own package.
=> feat: add package instrumentation-all to opencensus-node

packages/opencensus-core/src/exporters/exporter-buffer.ts, packages/opencensus-core/test/test-exporter-buffer.ts
The core unit tests take an unexpectedly long time before exiting... this change fixes that by `unref`'ing the `Timer` object used when doing periodic trace buffer flushing.
=> fix: unref ExporterBuffer flush timer

packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer.ts
=> fix: set currentRootSpan before start and set parentSpanId at span constructor

packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http2/package-lock.json, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts, packages/opencensus-instrumentation-https/package.json, packages/opencensus-instrumentation-https/src/https.ts, packages/opencensus-instrumentation-https/test/test-https.ts
This PR makes various type fixes. It also makes `traceStatus` a static function (as it should be).
=> refactor: privatize some non-user-facing Methods

packages/opencensus-core/src/trace/instrumentation/base-plugin.ts, packages/opencensus-core/src/trace/instrumentation/types.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts, packages/opencensus-instrumentation-https/src/https.ts, packages/opencensus-instrumentation-https/test/test-https.ts, packages/opencensus-instrumentation-mongodb/src/mongodb.ts, packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts, packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/@opencensus/instrumentation-load-internal-file-module/index.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/@opencensus/instrumentation-load-internal-file-module/load-internal-file-module.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/@opencensus/instrumentation-load-internal-file-module/package.json, packages/opencensus-nodejs/test/instrumentation/node_modules/@opencensus/instrumentation-simple-module/simple-module.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/enduser-simple-module-plugin/enduser-simple-module-plugin.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/load-internal-file-module/index.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/load-internal-file-module/package.json, packages/opencensus-nodejs/test/instrumentation/node_modules/load-internal-file-module/src/extra-module.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/simple-module/index.ts, packages/opencensus-nodejs/test/instrumentation/node_modules/simple-module/src/extra-module.ts, packages/opencensus-nodejs/test/test-plugin-loader.ts
Sometimes, there is a need to patch internal module files that are not exported by default. This PR aims to add a mechanism to make it possible to load internal files from a module and make it available to a plugin.
=> feat: add mechanism to load internal module files to patch

packages/opencensus-propagation-b3/src/b3-format.ts
The TODO left was: 
> TODO: Review this logic, maybe make it more robust. Question: are this logic valid if any of the `getHeader` operations returns a `string[]`.
I checked and `string[]` has the same behavior in this logic. `getHeader()` returns a `string | string[]`, the verification `isNaN(Number())` works for both.
=> refactor: address b3 propagation TODOs

packages/opencensus-propagation-stackdriver/src/v1.ts
This avoids deprecation warnings from Node.js core due to `import *`
of `crypto` in Node 10.
Example from a repo where I am using this module:
```
$ node --trace-deprecation build/system-test/foo.js
(node:19445) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
at __importStar (/Users/ofrobots/src/veneer/nodejs-logging-bunyan/node_modules/@opencensus/propagation-stackdriver/build/src/v1.js:20:96)
at Object.<anonymous> (/Users/ofrobots/src/veneer/nodejs-logging-bunyan/node_modules/@opencensus/propagation-stackdriver/build/src/v1.js:30:16)
at Module._compile (internal/modules/cjs/loader.js:702:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
at Module.load (internal/modules/cjs/loader.js:612:32)
at tryModuleLoad …
```
=> chore: use TS synthetic default imports

.circleci/config.yml
Since Node 9 is going [EOL this month](https://github.com/nodejs/Release#release-schedule), and Node 10 has been out for a while, this PR swaps out Node 9 CI testing with Node 10.
Fixes #44
=> chore: swap out node 9 testing on ci with node 10

packages/opencensus-nodejs/test/test-plugin-loader.ts
'intercept-stdout' used by 'test-plugin-loader.ts' was interfering in the visualization of tests results because a call to unhook was missing.
=> test: test-plugin-loader.ts - add a call to intercept-stdout unhook

packages/opencensus-nodejs/package.json
This new version allows for multiple versions of require-in-the-middle to be present in the same dependency-tree without interfering.
=> chore: bump require-in-the-middle to ^3.0.0

packages/opencensus-propagation-jaeger/.npmignore, packages/opencensus-propagation-jaeger/AUTHORS, packages/opencensus-propagation-jaeger/LICENSE, packages/opencensus-propagation-jaeger/README.md, packages/opencensus-propagation-jaeger/package-lock.json, packages/opencensus-propagation-jaeger/package.json, packages/opencensus-propagation-jaeger/src/index.ts, packages/opencensus-propagation-jaeger/src/jaeger-format.ts, packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts, packages/opencensus-propagation-jaeger/tsconfig.json
Jaeger uses a custom header for propagating span context. They are intending
to move to the w3c spec, but there is no clear time frame on that, lots of
existinng things using jaeger tracing will need this for now.
=> feat: add jaeger uber-trace-id header propagation

packages/opencensus-exporter-stackdriver/src/stackdriver.ts
I couldn't figure out how to get tests to pass locally, even without these changes. It seems to work if I copy the relevant lines into my project's dependency though.
=> feat: Map Span attributes to labels for Stackdriver export

packages/opencensus-exporter-instana/src/instana.ts
- expose error state based on `span.status`
- correctly map `span.kind` to Instana's span kinds
- remove now unnecessary binary operation
=> feat: Expand OpenCensus span data export to Instana

packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/stats/view.ts, packages/opencensus-core/test/test-view.ts
Add stats view implementation and its tests.
=> feat: add stats view implementation

packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts, packages/opencensus-exporter-jaeger/src/jaeger.ts, packages/opencensus-exporter-jaeger/test/test-jaeger.ts, packages/opencensus-exporter-jaeger/tsconfig.json
The typescript definition files weren't being generated for the exporter-jaeger package because the tsconfig didn't extend from the gts base config.
=> chore: add type definitions for exporter-jaeger

packages/opencensus-nodejs/README.md
in the startChildSpan method, there was a syntax error. I think someone copied from the TypeScript definitions and forgot to remove the variable name.
=> Fix syntax error in README

packages/opencensus-exporter-jaeger/src/jaeger.ts
Jaeger exporter was using a "debug" logger as a default, whereas all other
exporters simply use the default logger.
=> fix: use default logger in jaeger exporter

packages/opencensus-exporter-prometheus/.npmignore, packages/opencensus-exporter-prometheus/AUTHORS, packages/opencensus-exporter-prometheus/LICENSE, packages/opencensus-exporter-prometheus/README.md, packages/opencensus-exporter-prometheus/package-lock.json, packages/opencensus-exporter-prometheus/package.json, packages/opencensus-exporter-prometheus/src/index.ts, packages/opencensus-exporter-prometheus/src/prometheus-stats.ts, packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts, packages/opencensus-exporter-prometheus/tsconfig.json
This PR adds prometheus stats exporter to opencensus nodejs. Unit tests are included.
=> feat: add prometheus stats exporter to opencensus nodejs

README.md, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-propagation-tracecontext/AUTHORS, packages/opencensus-propagation-tracecontext/LICENSE, packages/opencensus-propagation-tracecontext/README.md, packages/opencensus-propagation-tracecontext/package-lock.json, packages/opencensus-propagation-tracecontext/package.json, packages/opencensus-propagation-tracecontext/src/index.ts, packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts, packages/opencensus-propagation-tracecontext/src/validators.ts, packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts, packages/opencensus-propagation-tracecontext/tsconfig.json
Based on w3c TraceContext spec: https://w3c.github.io/distributed-tracing/
The `traceparent` header is validated and propagated according to spec.
The only caveat is that the option flags are lost downstream and reset to
"0x1" by the tracer. This will require a refactor of how the tracer treats
the options as certain assumptions are being made that the least-significant
bit will always represent "sampled".
The `tracestate` is propagated downstream, but is currently not mutable by
the tracer. It is simply stored as a string, but types have been generated
to allow this to be refactored into a more structured type in the future,
allowing the tracer to update the tracestate as necessary.
This commit does not attempt to implement the `Correlation-Context` header.
issue #95
=> feat: add tracecontext propagation

packages/opencensus-exporter-zipkin/README.md, packages/opencensus-exporter-zipkin/src/zipkin.ts
This is just a feature that may be handy for users. The Zipkin URL asks for a specific format. This change adds a default URL making it optional.
=> feat: add a default zipkin url

packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/rpcz.controller.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/controllers/statsz.controller.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/routes.ts, packages/opencensus-exporter-zpages/src/zpages.ts, packages/opencensus-exporter-zpages/templates/rpcz.ejs, packages/opencensus-exporter-zpages/templates/span-cell.ejs, packages/opencensus-exporter-zpages/templates/statsz-directories.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-count.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-distribution.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-lastvalue.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-sum.ejs, packages/opencensus-exporter-zpages/templates/statsz-view.ejs, packages/opencensus-exporter-zpages/templates/statsz.ejs, packages/opencensus-exporter-zpages/templates/styles.min.css, packages/opencensus-exporter-zpages/templates/summary.ejs, packages/opencensus-exporter-zpages/templates/traceconfigz.ejs, packages/opencensus-exporter-zpages/templates/tracez.ejs, packages/opencensus-exporter-zpages/test/test-zpages.ts
This PR adds stats support to zpages exporter. Unit tests are included.
=> feat: add stats support to zpages exporter

packages/opencensus-instrumentation-http/src/http.ts
Strictly this should not happen, we should always get a spanContext,
however, this is not currently the case.
=> fix: don't attempt to propagate a null span.

packages/opencensus-core/src/internal/util.ts, packages/opencensus-propagation-b3/src/b3-format.ts, packages/opencensus-propagation-jaeger/src/jaeger-format.ts, packages/opencensus-propagation-stackdriver/package-lock.json, packages/opencensus-propagation-stackdriver/package.json, packages/opencensus-propagation-stackdriver/src/ext-types.d.ts, packages/opencensus-propagation-stackdriver/src/v1.ts, packages/opencensus-propagation-stackdriver/test/test-v1.ts
SpanIds in opencensus-node are currently generated, sent in traces, and propagated to other services as numeric values. This isn't consistent with other opencensus libraries (e.g.: [opencensus-java](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/trace/SpanId.java) serializes the span id as lowercase base16). When opencensus-node is setup with B3 propagation, this SpanId format violates the [B3 specification](https://github.com/openzipkin/b3-propagation#spanid-1) which mandates lowercase base16 encoding. Generally speaking, opencensus-java only accepts spans in this format so it will fail to correctly link to any span generated by opencensus-node. The best case scenario is a shared trace id with a missing parent span link.
This PR …
=> Fix SpanId generation for interoperability

packages/opencensus-core/package.json, packages/opencensus-core/scripts/compile.ts, packages/opencensus-core/scripts/utils.ts, packages/opencensus-core/src/stats/types.ts
This PR addresses the following:
- [Nodejs Quickstart](https://opencensus.io/quickstart/nodejs/metrics/#1) giving a _Cant read property MS of MeasureUnit_ error
- OpenCensus Core compile script giving a _The node cant find 'utils' module_ error.
- Warning for not recompiling the library with `strictNullChecks` enabled
=> fix: remove const enums

packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts
[exporter-stackdriver]
Solves the error:
UnhandledPromiseRejectionWarning: Error: Field timeSeries[0].points[0].distributionValue.range is not allowed: Distribution range is not yet supported.
=> Removes redundant range min/max from distributedValues

packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
- The metric type, including its DNS name prefix. The type is not URL-encoded. 
All user-defined metric types have the DNS name custom.googleapis.com or 
external.googleapis.com. Metric types should use a natural hierarchical grouping. 
For example: ""custom.googleapis.com/invoice/paid/amount"" 
""external.googleapis.com/prometheus/up"" 
""appengine.googleapis.com/http/server/response_latencies"""
=> Adds metric name prefix override for [exporter-stackdriver]

RELEASING.md
Thanks @kjin for putting together this document.
=> Add RELEASING.md.

packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
Hi, 
I made some changes to let stackdriver monitoring exporter upload metrics periodically, which are related to issue #152. Including:
1. Use `setInterval()` to schedule metrics uploading.
2. Add the `close()` method which can clear the setInterval timer.
3. Change the behavior of `.onRecord()` and related test cases, because metrics will not be uploaded when `.onRecord()` is called.
4. Make sure `.catch()` blocks in some test cases are executed by finishing them with mocha `done()`
5. Map all non `AggregationType.LAST_VALUE` to stackdriver `MetricKind.CUMULATIVE`.
=> Use setInterval to upload metrics to Stackdriver periodically

package-lock.json, packages/opencensus-core/package-lock.json, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-exporter-stackdriver/src/modules.d.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
I am not sure if this is the best place to change the spanId format. Another option would be to do it in the core/utils spanId generator, but I am not sure if other exporters or propagators expect the spanId to be in a certain format.
closes #161
=> fix spanId format

package-lock.json, packages/opencensus-core/package-lock.json, packages/opencensus-exporter-instana/package-lock.json, packages/opencensus-exporter-jaeger/package-lock.json, packages/opencensus-exporter-ocagent/package-lock.json, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-stackdriver/src/modules.d.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts, packages/opencensus-exporter-zipkin/package-lock.json, packages/opencensus-exporter-zpages/package-lock.json, packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-http/package-lock.json, packages/opencensus-instrumentation-http2/package-lock.json, packages/opencensus-instrumentation-https/package-lock.json, packages/opencensus-instrumentation-mongodb/package-lock.json, packages/opencensus-nodejs/package-lock.json, packages/opencensus-propagation-b3/package-lock.json, packages/opencensus-propagation-jaeger/package-lock.json, packages/opencensus-propagation-stackdriver/package-lock.json, packages/opencensus-propagation-tracecontext/package-lock.json
Uses `require` instead of `import` for `hex2dec` package due to type package for `hex2dec` will be available
=> Rename prefix name for [StackdriverStatsExporter]

package-lock.json, packages/opencensus-instrumentation-http/src/http.ts
instrumentation-http rely on `options.pathname` for outgoing request to name the span. However, several libraries are passing options directly to http.request which [save it as is](https://github.com/nodejs/node/blob/0d8021e5a4cf0a6aa3a700a361f6d42c2894f2ba/lib/_http_client.js#L90).
Affected libraries include:
- [node-fetch](https://github.com/bitinn/node-fetch) 1.x.x (can be solved by upgrading to 2.x.x)
- [request](https://github.com/request/request)
To reproduce, simply setup a tracer and fire an outgoing request with request. The trace will have the name of `GET undefined`.
This PR ensure that we parse every option for pathname instead of relying that it exists.
=> instrumentation-http: Parse URL instead of relying on pathname

packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
=> Exporter/Stats/Stackdriver: Fix MetricDescriptors ValueType

packages/opencensus-core/package.json, packages/opencensus-core/src/common/version.ts, packages/opencensus-core/src/index.ts, packages/opencensus-exporter-ocagent/src/ocagent.ts
Exports the current package version from the root level. This allows
users of this module to read the version of the library that has been
loaded.
=> Export package version

packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts
Calling randomBytes() only once to create a 24 byte buffer and converting it to hex and slicing the string then provides the same randomness while shaving off ~40% execution time.
**Testcode**
```js
const crypto = require('crypto');
function headerCallTwice() {
return {
traceId: crypto.randomBytes(16).toString('hex'),
spanId: crypto.randomBytes(8).toString('hex'),
traceState: undefined
};
}
function headerSliceBuffer() {
const buff = crypto.randomBytes(24);
return {
traceId: buff.slice(0, 16).toString('hex'),
spanId: buff.slice(16, 24).toString('hex'),
traceState: undefined
};
}
function headerSliceString() {
const buff = crypto.randomBytes(24).toString('hex');
return {
traceId: buff.slice(0, 32),
spanId: buff.slice(32, 48),
traceState: undefined
};
}
function timeFunc(f, n) {
const …
```
=> Performance: Use one 24 byte random buffer instead of calling randomBytes() twice

packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/exporter-buffer.ts, packages/opencensus-core/src/stats/view.ts, packages/opencensus-core/src/trace/instrumentation/base-plugin.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/sampler/sampler.ts, packages/opencensus-core/src/trace/types.ts, packages/opencensus-core/test/test-console-exporter.ts, packages/opencensus-core/test/test-console-logger.ts, packages/opencensus-core/test/test-exporter-buffer.ts, packages/opencensus-core/test/test-recorder.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-sampler.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-core/test/test-view.ts, packages/opencensus-core/tsconfig.json
Add ```--noUnusedLocals``` Compiler Options to disallows unused imports, variables, functions and
private class members.
=> Enforce "noUnusedLocals" : Report errors on unused locals.

CHANGELOG.md, packages/opencensus-core/package-lock.json, packages/opencensus-core/src/common/validations.ts, packages/opencensus-core/src/metrics/export/types.ts, packages/opencensus-core/src/metrics/gauges/gauge.ts, packages/opencensus-core/src/metrics/gauges/types.ts, packages/opencensus-core/src/metrics/utils.ts, packages/opencensus-core/test/test-gauge.ts, packages/opencensus-core/test/test-utils.ts
The Gauges API work is split into multiple PRs. This is the second installment.
Completed:
**- Add metric registry and validations util** (https://github.com/census-instrumentation/opencensus-node/pull/203)
Current:
- Add Double and INT64 Gauges APIs
Next in line:
- Plug-in gauges into the registry.
- Add derived gauges API and Plug-in gauges into the registry.
- Add Metric Collector interface.
- Register Metric-Registry with MetricProducer.
=> Add Double and INT64 Gauges APIs

CHANGELOG.md, packages/opencensus-core/package-lock.json, packages/opencensus-core/src/metrics/gauges/derived-gauge.ts, packages/opencensus-core/test/test-derived-gauge.ts
The Gauges API work is split into multiple PRs.
**Completed:**
- Add metric registry and validations util (#203)
- Add Double and INT64 Gauges APIs (#207)
**Current:**
- Add derived gauges API (This is a more convenient API when users want to define a gauge by executing extractor on object/collection. The ```ValueExtractor``` is invoked whenever metrics are collected, meaning the reported value is up-to-date).
**Next in line:**
- Plug-in gauges into the registry and register Metric-Registry with MetricProducer.
=> Add derived gauge API

packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/test/test-metric-registry.ts
The Gauges API work is split into multiple PRs.
**Completed:**
- Add metric registry and validations util (#203)
- Add Double and INT64 Gauges APIs (#207)
- Add derived gauges API (#220)
- Plug-in gauges into the registry and register Metric-Registry with MetricProducer (#223)
**Current:** 
- Plug-in derived-gauges into the registry
**Next:**
- Add MetricProducerManager to keep track of all MetricProducers i.e. MetricProducerForRegistry and MetricProducerForStats
=> Plug-in derived-gauges into the Metric-Registry

packages/opencensus-exporter-zipkin/src/zipkin.ts
In order to follow a `Zipkin` [Span](https://github.com/openzipkin/zipkin/blob/9b91acbaa3b90ad1c9e4ab62489db05dfd9edf74/zipkin/src/main/java/zipkin2/Span.java#L289) specification, I'm proposing to change `string` type to `number` for `timestamp` and `duration`.
=> Converting `timestamp` and `duration` to the `number` type to follow Zipkin span types

.circleci/config.yml, package.json, packages/opencensus-core/codecov.yml, packages/opencensus-core/package-lock.json, packages/opencensus-core/package.json, packages/opencensus-exporter-prometheus/codecov.yml, packages/opencensus-exporter-prometheus/package-lock.json, packages/opencensus-exporter-prometheus/package.json, packages/opencensus-exporter-stackdriver/codecov.yml, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-nodejs/codecov.yml, packages/opencensus-nodejs/package-lock.json, packages/opencensus-nodejs/package.json
This PR starts reporting code coverage. If all goes well, coverage should be at https://codecov.io/gh/census-instrumentation/opencensus-node
For now, I have considered four packages (```nodejs```, ```core```, ```exporter-prometheus``` and ```exporter-stackdriver```) for codecov. If all goes well, I will expand this for other packages.
=> Codecov: start reporting code coverage.

examples/stats/web_client_monitoring/README.md
change to parent instead of home directory
=> Minor change to README file

packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/types.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-exporter-prometheus/src/prometheus-stats.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-zpages/src/zpages.ts
With the current approach, we execute below apis for each request of new view and measurement.
```onRegisterView``` - whenever a new view is registered and 
```onRecord``` - whenever a new measurement is recorded. 
**New approach:** The plan is to start exporter that polls Metric from Metrics library (which is collection of metric from stats and gauges apis) and send **batched** data to backend. 
_Once the new approach is ready I will deprecate and remove ```onRegisterView```  and  ```onRecord``` apis._
=> Add start method to StatsEventListener

package-lock.json, packages/opencensus-core/package-lock.json, packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts
This PR is part of #257, Basically, ```StackdriverStatsExporterUtils``` methods will be used by ```StackdriverStatsExporter``` to translate data from OpenCensus data models to StackDriver monitoring data models. I will send separate PR to include this util in ```StackdriverStatsExporter```.
=> Add helper util to convert OC Metrics data models to SD monitoring data models

CHANGELOG.md, packages/opencensus-core/src/common/console-logger.ts, packages/opencensus-core/src/common/types.ts, packages/opencensus-core/test/test-console-logger.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
By removing `silly` and making the `level` attribute optional (and defaulted to `debug`) then the `console` interface itself will implement `Logger`. See [this TS playground](http://www.typescriptlang.org/play/#src=export%20type%20LogFunction%20%3D%20(message%3A%20any%2C%20...args%3A%20any%5B%5D)%20%3D%3E%20void%3B%0D%0A%0D%0A%2F**%20Defines%20an%20logger%20interface.%20*%2F%0D%0Aexport%20interface%20Logger%20%7B%0D%0A%20%20level%3F%3A%20string%3B%0D%0A%20%20error%3A%20LogFunction%3B%0D%0A%20%20warn%3A%20LogFunction%3B%0D%0A%20%20info%3A%20LogFunction%3B%0D%0A%20%20debug%3A%20LogFunction%3B%20%20%0D%0A%7D%0D%0A%0D%0Aconst%20logger%3A%20Logger%20%3D%20console%3B)
This will be useful for `opencensus-web` where a major goal is small code size for web clients, so being able to just use …
=> Simplify Logger interface, remove silly, make level optional

packages/opencensus-core/src/stats/stats.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
This PR is part of #257 
The majority of work has been handled/covered in  ```StackdriverStatsExporterUtils ``` https://github.com/census-instrumentation/opencensus-node/pull/266, this PR is based on that work to export data to backend.
=> Stats/Stackdriver: export data using metrics API 

packages/opencensus-core/src/stats/view.ts, packages/opencensus-core/test/test-view.ts
Validates tagkey & tagvalues as per the specification given in https://github.com/census-instrumentation/opencensus-specs/blob/master/tags/TagMap.md#tagkey
ran `npm test` & `npm run complie` with no errors.
=> Add validation for tagkey & tagvalue. Fix issue #268

.gitignore, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/tags/tag-map.ts, packages/opencensus-core/src/tags/types.ts, packages/opencensus-core/src/tags/validation.ts, packages/opencensus-core/test/test-tag-map.ts, packages/opencensus-core/test/test-validation.ts
This PR is based on specs : https://github.com/census-instrumentation/opencensus-specs/blob/master/tags/TagMap.md#tagkey
=> [core] Add Tags API

CHANGELOG.md, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/resource/resource.ts, packages/opencensus-core/test/test-resource.ts, packages/opencensus-resource-util/AUTHORS, packages/opencensus-resource-util/LICENSE, packages/opencensus-resource-util/README.md, packages/opencensus-resource-util/codecov.yml, packages/opencensus-resource-util/package-lock.json, packages/opencensus-resource-util/package.json, packages/opencensus-resource-util/src/index.ts, packages/opencensus-resource-util/src/resource-labels.ts, packages/opencensus-resource-util/src/types.ts, packages/opencensus-resource-util/tsconfig.json
Add util to automatically detect monitored resources based the environment that the application is running in, according to [OpenCensus MonitoredResource specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/utils/MonitoredResource.md). This util should be independent of specific exporters, since it's supposed to be share between Stackdriver Stats exporter and Stackdriver Trace exporter.
Counterpart in Java: https://github.com/census-instrumentation/opencensus-java/tree/master/contrib/monitored_resource_util.
This PR contains:
1. Initial package skeleton.
2. resource label constants.
3. export core resource types and class from core package.
=> Add `opencensus-resource-util` package

CHANGELOG.md, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/stats/metric-producer.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/test/test-metric-producer.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts, packages/opencensus-exporter-zpages/test/test-zpages.ts
This PR is based on #276.
This PR contains two breaking changes:
1. The ```new Stats()``` has been deprecated on Stats class. The global singleton ```globalStats``` object should be used instead.
2. ```registerView()``` hook has been removed from ```createView()``` API. This is related to https://github.com/census-instrumentation/opencensus-node/issues/287.
Fixes #290 #276
=>  Make Stats singleton (globalStats), separate registerView from createView

CHANGELOG.md, packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/types.ts, packages/opencensus-core/src/stats/metric-utils.ts, packages/opencensus-core/src/stats/recorder.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/stats/view.ts, packages/opencensus-core/src/tags/tag-map.ts, packages/opencensus-core/src/tags/validation.ts, packages/opencensus-core/test/test-metric-producer.ts, packages/opencensus-core/test/test-metric-utils.ts, packages/opencensus-core/test/test-recorder.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-core/test/test-view.ts, packages/opencensus-exporter-prometheus/src/prometheus-stats.ts, packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages.ts, packages/opencensus-exporter-zpages/templates/statsz-view-count.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-distribution.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-lastvalue.ejs, packages/opencensus-exporter-zpages/templates/statsz-view-sum.ejs, packages/opencensus-exporter-zpages/test/test-zpages.ts
Fixes #305 
This PR contains breaking API changes, highlighted in the CHANGELOG with old and new code.
=> Update stats, zpages, prometheus packages with new Tags API

packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts, packages/opencensus-exporter-stackdriver/test/nocks.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts, packages/opencensus-resource-util/src/resource-utils.ts, packages/opencensus-resource-util/test/test-detect-resource.ts
Fixes https://github.com/census-instrumentation/opencensus-node/issues/130
=> Stats/Stackdriver: Use resource util to generate MonitoredResource

packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-stackdriver/package.json
The new version has support(feat.) for adding user agent as a client header (https://github.com/googleapis/nodejs-googleapis-common/pull/76/files), will unblock long pending issue: https://github.com/census-instrumentation/opencensus-node/issues/194 and PR: https://github.com/census-instrumentation/opencensus-node/pull/214.
**Other noticeable changes for us:**
- fix: accept lowercase env vars (https://github.com/googleapis/google-auth-library-nodejs/pull/578)
-  use gaxios for HTTP requests instead of axios (https://github.com/googleapis/google-auth-library-nodejs/pull/593)
=> update googleapis -> 37.1.0

packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
=> Stats/Stackdriver: Add user agent as client header

packages/opencensus-exporter-stackdriver/src/common-utils.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-stats-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-stats-utils.ts, packages/opencensus-resource-util/src/resource-labels.ts
This PR contains common utils which is shared between stats and trace exporter especially to get default resources and its SD specific mappings. Also, removed some unused imports (I am planning to enforce ```"noUnusedLocals": true``` very soon on SD package) and ```AWS_REGION_VALUE_PREFIX``` constant moved in exporter as this prefix is only important to SD.
This PR is foundation for issuse #39.
=> Exporter/Stackdriver: Add common utils

CHANGELOG.md, packages/opencensus-core/src/trace/model/types.ts
This will be useful for the `opencensus-web` project since message sizes are often known in the browser performance timing API and I'd like to make it include message events per the [OpenCensus HTTP specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/HTTP.md).
=> Add message event size fields

CHANGELOG.md, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-exporter-instana/src/instana.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts, packages/opencensus-instrumentation-https/test/test-https.ts
=> Tracing: Add code and message to Span -> Status

packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts
This PR will address the second part (enforce limits on links) of #316
=> Enforce Links limit

packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts
Fixes #316
This PR will address the last part (enforce limits on message event and annotation) of #316
=> Enforce message event and annotation limits.

CHANGELOG.md, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-console-exporter.ts, packages/opencensus-core/test/test-exporter-buffer.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-exporter-instana/src/instana.ts, packages/opencensus-exporter-instana/test/test-instana.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts, packages/opencensus-exporter-zipkin/test/test-zipkin.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-mongodb/src/mongodb.ts, packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
=> Use enum for MessageEvent Type, Link Type and SpanKind

README.md, examples/stats/exporter/prometheus.js, examples/stats/exporter/stackdriver.js, examples/stats/web_client_monitoring/app.js, package.json, packages/opencensus-core/README.md, packages/opencensus-core/package.json, packages/opencensus-exporter-prometheus/README.md, packages/opencensus-exporter-stackdriver/README.md, packages/opencensus-exporter-stackdriver/package.json
This PR contains updated examples based on CHAGELOG -> https://github.com/census-instrumentation/opencensus-node/blob/master/CHANGELOG.md#new-code
Also, added ReadMe for the Stackdriver Stats(Metrics) exporter.
=> Update examples to work with global stats instance

CHANGELOG.md, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/nocks.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
=> Exporter/Stackdriver: Use Trace SDKs (v2 API)

lerna.json, packages/opencensus-core/package.json, packages/opencensus-example-automatic-tracing/package.json, packages/opencensus-exporter-instana/package.json, packages/opencensus-exporter-jaeger/package.json, packages/opencensus-exporter-ocagent/package.json, packages/opencensus-exporter-prometheus/package.json, packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-exporter-zipkin/package.json, packages/opencensus-exporter-zpages/package.json, packages/opencensus-instrumentation-all/package.json, packages/opencensus-instrumentation-grpc/package.json, packages/opencensus-instrumentation-http/package.json, packages/opencensus-instrumentation-http2/package.json, packages/opencensus-instrumentation-https/package.json, packages/opencensus-instrumentation-mongodb/package.json, packages/opencensus-nodejs/package.json, packages/opencensus-propagation-b3/package.json, packages/opencensus-propagation-jaeger/package.json, packages/opencensus-propagation-stackdriver/package.json, packages/opencensus-propagation-tracecontext/package.json, packages/opencensus-resource-util/package.json
https://github.com/census-instrumentation/opencensus-node/releases/tag/untagged-7bad17fe5e1fb5d187af
**Feature and Bug Fixes**
55a5545 Exporter/Stackdriver: Use Trace SDKs (v2 API) (#338)
cb97d3f Update examples to work with global stats instance (#339)
95be16e Use enum for MessageEvent Type, Link Type and SpanKind (#334)
a692467 Enforce message event and annotation limits. (#335)
e95a418 Enforce Links limit (#331)
923148a Enforce attribute limit (#330)
57b1da5 Tracing: Add code and message to Span -> Status (#328)
94cc98c Add message event size fields (#323)
c10212f Add common utils (#321)
f98ec08 Add trace params (#311)
2a13a77 Stats/Stackdriver: Add user agent as client header (#320)
54d46ea Add timeout for AWS MetadataAccessor (#318)
4daea53 Stats/Stackdriver: Use resource util to …
=> chore(multiple): 0.0.9 release proposal

CHANGELOG.md, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-span.ts
Message size parameters were added in https://github.com/census-instrumentation/opencensus-node/pull/323 and this now adds them to the `addMessageEvent` function on span as optional parameters.
This also adds a comment to the `id` field of the `MessageEvent` interface to explain that it is a hexadecimal string that should increment as new messages are sent.
cc/ @odeke-em
=> Add message sizes to `addMessageEvent` function

packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/test/test-http.ts
I got the same issue as #117 while integrating the tracing system into my APM.
I did go over https://github.com/googleapis/cloud-trace-nodejs/ to checkout their implementation and found a details that could explain the problem: https://github.com/googleapis/cloud-trace-nodejs/blob/master/src/plugins/plugin-http.ts#L198
The test are passing for one good reason: they are all `nocked`, so the actual http code never run. I added a test that make a GET request to `google.fr`, it might be better to spawn a local server to avoid instability due to network.
=> fixes http.get patches for header propagation #117

packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts
This will fix the issue when we export data to Stackdriver backend https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts#L120, otherwise the program will crash when optional ```attributes``` is missing. 
I have open an issue #348 to enable ```strictNullChecks ``` on this repo.
=> add default value when `attributes` are not specified

packages/opencensus-instrumentation-grpc/package.json, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts, packages/opencensus-instrumentation-grpc/tsconfig.json, packages/opencensus-propagation-binaryformat/src/index.ts
Based on: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/gRPC.md#propagation
This PR contains below things
1. Use default binary format instead of B3 format.
2. Enforce ```strictNullChecks``` on grpc repo. (part of #348)
3. Enforce ```noUnusedLocals``` on grpc repo.
4. Update ```index.ts``` for ```[opencensus-propagation-binaryformat]``` package.
=> Use binary format for grpc plugin

CHANGELOG.md, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-exporter-instana/test/test-instana.ts, packages/opencensus-exporter-zipkin/test/test-zipkin.ts, packages/opencensus-exporter-zpages/test/test-zpages.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-mongodb/src/mongodb.ts
This will make things consistent with ```startRootSpan``` function. Currently,  ```startChildSpan``` function takes three arguments instead of an object.
To avoid breaking changes, I have introduced three favors of ```startChildSpan``` overloaded function.
=> Add option of passing in an object(SpanOptions) to the startChildSpan

CHANGELOG.md, packages/opencensus-exporter-ocagent/README.md, packages/opencensus-exporter-ocagent/package-lock.json, packages/opencensus-exporter-ocagent/package.json, packages/opencensus-exporter-ocagent/src/ocagent.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts
The `exporter-ocagent` had two critical issues which left the exporter unusable:
1. The required grpc proto files were not being referenced correctly (#174)
2. The `ConfigStream` behavior (where the ocagent can send configuration changes down to the client) was not connecting / receiving correctly from the ocagent, causing errors and spamming logs
The following changes have been applied to fix the above issues:
1. We now package the proto files for both OpenCensus and the google common proto set into the final `@opencensus/exporter-ocagent` package. The changes mostly reside in the `package.json` configuration.
2. We have removed all references to the `ConfigStream` behavior. This is a breaking change, but the ocagent exporter was not in a usable form previously, so I don't expect there …
=> Fix the exporter-ocagent

packages/opencensus-core/src/trace/instrumentation/base-plugin.ts, packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-grpc/package.json, packages/opencensus-instrumentation-grpc/src/grpc-stats/client-metrics.ts, packages/opencensus-instrumentation-grpc/src/grpc-stats/common-distributions.ts, packages/opencensus-instrumentation-grpc/src/grpc-stats/server-metrics.ts, packages/opencensus-instrumentation-grpc/src/grpc-stats/stats-common.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-grpc/src/index.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts
This PR is to get the ball rolling, Unit tests are still pending. Reviews are welcome at this moment.
Fixes #270 
```client-metrics.ts``` and ```server-metrics.ts```  are updated with minor nits.
Update: Tests are included now.
=> Add support for recording gRPC stats

packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-root-span.ts
Fixes #306  
This is based on spec: See https://github.com/census-instrumentation/opencensus-proto/blob/6d79e46232e026136ae013489ef611ca721cb839/src/opencensus/proto/trace/v1/trace.proto#L302.
=>  Add support for child span count

examples/stats/exporter/package.json, examples/stats/exporter/prometheus.js, examples/stats/exporter/stackdriver.js
The 0 bounds are removed from example bucket boundaries to match specs here : https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/metrics/v1/metrics.proto#L223
=> Update examples with latest OC version and format using semistandard

.circleci/config.yml
I am optimistic about tests and build, Let's see how much work required to add support for node 11.
=> chore: add node 11 ci job

CHANGELOG.md, packages/opencensus-instrumentation-grpc/src/index.ts, packages/opencensus-instrumentation-http/src/http-stats.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/src/index.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http/tsconfig.json
This PR provides instrumentation for HTTP Client and Server to record HTTP stats. Part of https://github.com/census-instrumentation/opencensus-node/issues/269
These changes have all been tested locally against prometheus exporter and been confirmed to be working.
I will work on recording stats for send/received bytes in seperate PR.
=> Add support for recording HTTP stats

.circleci/config.yml, packages/opencensus-instrumentation-redis/.npmignore, packages/opencensus-instrumentation-redis/AUTHORS, packages/opencensus-instrumentation-redis/LICENSE, packages/opencensus-instrumentation-redis/README.md, packages/opencensus-instrumentation-redis/codecov.yml, packages/opencensus-instrumentation-redis/package-lock.json, packages/opencensus-instrumentation-redis/package.json, packages/opencensus-instrumentation-redis/src/index.ts, packages/opencensus-instrumentation-redis/src/redis.ts, packages/opencensus-instrumentation-redis/test/test-redis.ts, packages/opencensus-instrumentation-redis/tsconfig.json
Not sure if everything is okay it terms of setup since i don't use lerna a lot, same with circleCI.
I've set the version to 0.0.1 but i believe you guys have all the packages at the same version for now, feel free to do it as you want.
I also choose not to add it into the `instrumentation-all` packages directly too, but i could do another PR if the plugin in itself is good.
cc @draffensperger @mayurkale22
=> implement redis instrumentation plugin

packages/opencensus-instrumentation-mongodb/package-lock.json, packages/opencensus-instrumentation-mongodb/src/mongodb.ts, packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts
From my tests all the mongodb queries had the wrong duration so i inspected the code and found out that the span were never ended and automatically truncated when the root span is ended.
So i rewrote a little bit the patchs so they could correctly be ended and added the verification in the tests
cc @draffensperger @mayurkale22
=> Fix mongodb instrumentation not ending span correctly

packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-grpc/package.json
Upgrading to ```typescript@2.8.3``` fixed the build issue on gRPC package.
=> Fix Build : "Cannot find name 'Exclude"

packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts, packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts, packages/opencensus-propagation-tracecontext/tsconfig.json
=> Propagation/TraceContext: Enforce strictNullChecks and noUnusedLocals

package-lock.json
=== npm audit security report ===                        
**Package**  =>  handlebars                                                
**Dependency of** => lerna [dev]       
**Path** =>   lerna > conventional-changelog-cli > conventional-changelog > conventional-changelog-core > conventional-changelog-writer > handlebars 
**More info** =>   [https://www.npmjs.com/advisories/755](https://www.npmjs.com/advisories/755)
=> Fix vulnerability : handlebars

CHANGELOG.md, packages/opencensus-exporter-instana/README.md, packages/opencensus-exporter-instana/src/instana.ts, packages/opencensus-exporter-instana/test/test-instana.ts, packages/opencensus-exporter-instana/tsconfig.json
=>  Exporter/Instana: Enforce strictNullChecks and noUnusedLocals

CHANGELOG.md, packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-console-exporter.ts, packages/opencensus-core/test/test-exporter-buffer.ts, packages/opencensus-core/test/test-no-record-root-span.ts, packages/opencensus-core/test/test-no-record-span.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-sampler.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-core/test/test-tracer.ts
Specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md#how-can-users-control-the-sampler-that-is-used-for-sampling
The logic for allocating ```traceId``` moved in ```tracer``` class. This helps to make sampling decision first and depending on decision we can then create either ```RecordRootSpan(RootSpan)``` or ```NoRecordRootSpan``` instead of always creating ```RootSpan```(just to get traceId for sampling decision) and discarding it later. 
This introduces signature changes to internal ```RootSpan``` class, But I think this won't be breaking change for users.
Fixes #391
=> Add support for overriding sampling per span

CHANGELOG.md, packages/opencensus-exporter-jaeger/README.md, packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts, packages/opencensus-exporter-jaeger/src/jaeger.ts, packages/opencensus-exporter-jaeger/test/test-jaeger.ts, packages/opencensus-exporter-jaeger/tsconfig.json
=> Exporter/jaeger: Enforce strictNullChecks and noUnusedLocals

packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-console-exporter.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts, packages/opencensus-nodejs/src/trace/tracing.ts, packages/opencensus-nodejs/test/test-plugin-loader.ts, packages/opencensus-nodejs/test/test-tracing.ts, packages/opencensus-nodejs/tsconfig.json
This PR contains following things
1. Remove unsed ```parentSpanId``` from ```startChildSpan``` API.
2. Code refactor/enhancement.
3. Enforce ```noUnusedLocals ``` on opencensus-nodejs package.
=> Code Enhancement/Refactor

packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts
See #301.
It seems like this was done for developer convenience, and this function is only used in this file. While I don't have a problem with that in principle, it breaks things for Webpack.
Remove the require wrapper and make the requires direct
See that the build still builds correctly.
=> Jaeger exporter: remove require wrapper and make requires direct

packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts, packages/opencensus-instrumentation-http2/tsconfig.json, packages/opencensus-instrumentation-https/src/https.ts, packages/opencensus-instrumentation-https/test/test-https.ts, packages/opencensus-instrumentation-https/tsconfig.json
```strictNullChecks``` will help us to make the code safer (referencing nulls or undefined values), more robust and reduce some boilerplate.
This is part of #348
=> Instrumentation/HTTP2/HTTPS: Enforce strictNullChecks and noUnusedLocals

CHANGELOG.md, packages/opencensus-core/src/stats/recorder.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/stats/view.ts, packages/opencensus-core/test/test-recorder.ts, packages/opencensus-core/test/test-view.ts
Specs: https://github.com/census-instrumentation/opencensus-specs/blob/18ddbd73ffc6786622fb17a9f1798d6b668fded2/stats/Exemplars.md
Fixes #385
=>  Add support for recording exemplars

packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring-utils.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/tsconfig.json
=> Exporter/Stackdriver: Enforce strictNullChecks and noUnusedLocals

examples/stats/exporter/prometheus.js, package-lock.json, packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/stats/view.ts, packages/opencensus-exporter-prometheus/README.md, packages/opencensus-exporter-prometheus/src/prometheus-stats.ts, packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts, packages/opencensus-exporter-prometheus/tsconfig.json
=> Exporter/Prometheus: Enforce strictNullChecks and noUnusedLocals

packages/opencensus-instrumentation-http/src/http.ts
=> Use options.host instead of options.hostname (#416)

packages/opencensus-instrumentation-ioredis/.npmignore, packages/opencensus-instrumentation-ioredis/AUTHORS, packages/opencensus-instrumentation-ioredis/LICENSE, packages/opencensus-instrumentation-ioredis/README.md, packages/opencensus-instrumentation-ioredis/codecov.yml, packages/opencensus-instrumentation-ioredis/package-lock.json, packages/opencensus-instrumentation-ioredis/package.json, packages/opencensus-instrumentation-ioredis/src/index.ts, packages/opencensus-instrumentation-ioredis/src/ioredis.ts, packages/opencensus-instrumentation-ioredis/test/test-ioredis.ts, packages/opencensus-instrumentation-ioredis/tsconfig.json
cc @mayurkale22 @draffensperger
=> add ioredis instrumentation plugin

packages/opencensus-propagation-b3/src/b3-format.ts, packages/opencensus-propagation-b3/src/validators.ts, packages/opencensus-propagation-b3/test/test-b3-format.ts, packages/opencensus-propagation-b3/tsconfig.json
=> Propagation/B3: Enforce strictNullChecks and noUnusedLocals

examples/tags/tag-context-example.js, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/internal/cls-ah.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/src/tags/tag-map.ts, packages/opencensus-core/src/tags/tagger.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-core/test/test-tagger.ts
Specs are available here: https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/Record.md#recording-stats
This will allow users to set and get the current tag context, which can be used when recoding the stats if explicit tags are not provided.
=> Stats: Record against implicit (current) tag context

packages/opencensus-exporter-zpages/src/zpages-frontend/latency-bucket-boundaries.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages.ts, packages/opencensus-exporter-zpages/test/test-zpages.ts, packages/opencensus-exporter-zpages/tsconfig.json
This is part of #348. 3 more packages to go, 19 done so far.
=> opencensus-zpages: Enforce strictNullChecks and noUnusedLocals

packages/opencensus-exporter-zpages/package-lock.json, packages/opencensus-exporter-zpages/package.json, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/rpcz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/statsz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/traceconfigz.page-handler.ts, packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
The `@types/pkg-dir` package has been deprecated. https://www.npmjs.com/package/@types/pkg-dir
=> Remove deprecated @types/pkg-dir and pkg-dir 

packages/opencensus-propagation-stackdriver/package.json, packages/opencensus-propagation-stackdriver/src/index.ts, packages/opencensus-propagation-stackdriver/src/stackdriver-format.ts, packages/opencensus-propagation-stackdriver/src/v1.ts, packages/opencensus-propagation-stackdriver/test/test-stackdriver-format.ts, packages/opencensus-propagation-stackdriver/test/test-v1.ts, packages/opencensus-propagation-stackdriver/tsconfig.json
This PR fixes two things:
1. Stackdriver propagation exports an implementation of Propagation, while `B3`, `Binary Format`, `TraceContext` and `Jaeger` propagation exports a class constructor. Fixes #340
2. Enforce `strictNullChecks` and `noUnusedLocals` on Stackdriver propagation package. This is part of #348
=> Make Stackdriver propagation module consistent with other propagations interface

packages/opencensus-core/src/tags/propagation/binary-serializer.ts, packages/opencensus-core/src/tags/propagation/variant-encoding.ts, packages/opencensus-core/test/test-binary-serializer.ts, packages/opencensus-core/test/test-variant-encoding.ts
=> Add support for Binary Format serializer for TagMap

packages/opencensus-core/src/internal/cls.ts
We shipped our APM with the `@opencensus/core` package. We didn't enable the tracer by default but since when required, it will require the `continuation-local-storage` which will apply patches automatically. So even if you use `async_hooks`, you will have the patchs from the userland CLS.
I believe it's safe to change this behavior since it will work the same way.
I would like to raise also the fact that we could only require both CLS implementation when the tracing is enabled to decrease the performance impact when not enabled.
If you are interested, here are the different complaints from users: https://github.com/keymetrics/pm2-io-apm/issues/235
=> only require userland CLS when needed

packages/opencensus-propagation-jaeger/README.md, packages/opencensus-propagation-jaeger/src/jaeger-format.ts, packages/opencensus-propagation-jaeger/src/validators.ts, packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts, packages/opencensus-propagation-jaeger/tsconfig.json
This is part of #348. 2 more packages to go, 20 done so far.
=> Propagation-Jaeger: Enforce strictNullChecks and noUnusedLocals

CHANGELOG.md, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/tags/propagation/text-format.ts, packages/opencensus-core/test/test-text-format.ts
Updates #297  This is the HTTP version of of #431.
Based on **W3C correlation context format**: https://github.com/w3c/correlation-context/blob/master/correlation_context/HTTP_HEADER_FORMAT.md
There will be another PR to use these serializer functions in the HTTP plugin to propagate tags on wire.
=> Add HTTP/W3C text format serializer to Tag propagation component

examples/tags/tag-context-example.js, packages/opencensus-core/src/index.ts, packages/opencensus-core/src/internal/cls-ah.ts, packages/opencensus-core/src/internal/cls.ts, packages/opencensus-core/src/stats/stats.ts, packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/tags/tagger.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/test/test-stats.ts, packages/opencensus-core/test/test-tagger.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts
Fixes #325
This PR contains the following changes
1. Share same `contextManager` across tracer and stats singleton instances.
2. Add `withTagContext` and `getCurrentTagContext ` API on stats, so that plugins can use these API to get current `TagContext/TagMap`.
3. Make a deep copy of `TagMap` during get/set into `contextManager`.
4. Insert/Get gRPC metadata with `grpc-tags-bin` header with serialized `TagMap`.
5. Update `tag-context-example.js` example.
=> Add support for gRPC tags propagation

.circleci/config.yml, package.json
These will help us to detect style related errors at an early stage instead of while executing unit or system tests.
=> Add code style checker in unit test workflow

packages/opencensus-core/src/metrics/gauges/types.ts, packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/test/test-metric-registry.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring.ts
The list of options are too long for `Gauges` (`Cumulative` metrics - in the future) metrics and most of them are optional. It makes sense to use `MetricOptions` type to maintain the options. Also, in the future will be adding `resource` information to the `MetricOptions` list. This way it is easier to shrink or expand the input options.
Although, this is a breaking change in existing `Gauge` API but we don't expect too many users using this (released in last version - `0.0.9`).
Specs: https://github.com/census-instrumentation/opencensus-specs/pull/248/files
=> Add MetricOptions to simplify all addXGauge

examples/http/client.js, examples/http/package.json, examples/http/server.js, packages/opencensus-core/src/trace/config/types.ts, packages/opencensus-nodejs/src/trace/instrumentation/plugin-loader.ts, packages/opencensus-nodejs/src/trace/tracing.ts
Allow a way to pass ```stats``` instance to ```PluginLoader``` class, this will help users to collect stats for HTTP and GRPC plugin with automatic tracing. 
Also, I have updated the HTTP instrumentation example to capture traces without manually enabling the plugin.  I think this is the recommended and straightforward way for users to enable tracing on supported plugins/frameworks.
=> pass stats instance to plugin loader

examples/gauge/derived-gauge-quickstart.js, examples/gauge/gauge-quickstart.js
=> Add gauge example

CHANGELOG.md, packages/opencensus-core/src/trace/model/no-record/no-record-span-base.ts, packages/opencensus-core/src/trace/model/span-base.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-no-record-root-span.ts, packages/opencensus-core/test/test-no-record-span.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/test/test-ocagent.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-zipkin/test/test-zipkin.ts, packages/opencensus-instrumentation-grpc/src/grpc.ts, packages/opencensus-instrumentation-http/package-lock.json, packages/opencensus-instrumentation-http/package.json, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http2/package-lock.json, packages/opencensus-instrumentation-http2/package.json, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts
Fixes #442 
As per the [Specs](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace.proto#L202-L206), The `MessageId` must be calculated as two different counters starting from 1 one for sent messages and one for received message. This way we guarantee that the values will be consistent between different implementations.
~~To avoid breaking changes, I preferred to keep `string` type for id field. I am happy to change that or add support for both `string|number`.~~
=> Message events: use counters instead of hexdecimal value

CHANGELOG.md, packages/opencensus-core/src/common/validations.ts, packages/opencensus-core/src/metrics/gauges/derived-gauge.ts, packages/opencensus-core/src/metrics/gauges/gauge.ts, packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/test/test-derived-gauge.ts, packages/opencensus-core/test/test-gauge.ts, packages/opencensus-core/test/test-metric-registry.ts
This is as per the specs: https://github.com/census-instrumentation/opencensus-specs/pull/248
=>  Gauge: Add support for constant labels

packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts
Fixes #429 
**DeprecationWarning**: The `createScopedRequired` method on the `JWT` class has been deprecated, and will be removed in the 3.0 release of google-auth-library.
These changes have all been tested locally and been confirmed to be working.
=> Fix: createScopedRequired depcreated in google-auth-library 3.0.0

packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
- compressedSize -> compressedSizeBytes
- uncompressedSize -> uncompressedSizeBytes
I've told my boss that last bug fix and publishing 0.0.10 milestone will be the cure for failing opencensus instrumentation last week and it seems like I'd need to wait more
going for a beer cheers!
=> Fix error in opencensus to stackdriver translation (#474)

CHANGELOG.md, packages/opencensus-exporter-jaeger/src/jaeger-driver/index.ts, packages/opencensus-exporter-jaeger/test/test-jaeger.ts
=> Add support for Opencensus Span links to Thrift Span references

README.md, packages/opencensus-instrumentation-all/package-lock.json, packages/opencensus-instrumentation-all/package.json, packages/opencensus-instrumentation-all/src/index.js, packages/opencensus-nodejs/README.md
As mentioned before, adding a new plugin to the default list need 2 different global release currently:
- the first one to push it to npm and add it as a dependency of the `instrumentation-all` module
- and the second to publish the new version of `instrumentation-all` so the new plugin are enabled by default.
We might want to change that to release new plugins faster. How do you think we could do that ?
=> add redis instrumentation plugins by default

packages/opencensus-core/src/index.ts, packages/opencensus-core/src/metrics/cumulative/cumulative.ts, packages/opencensus-core/src/metrics/cumulative/types.ts, packages/opencensus-core/src/metrics/gauges/derived-gauge.ts, packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/src/metrics/types.ts, packages/opencensus-core/test/test-cumulative.ts
Updates #450 
Adding **Derived Cumulative API** and registering with **[Metric-Registry](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/metrics/metric-registry.ts)** will be in a follow-up PR.
=> Add support for Cumulative API

packages/opencensus-exporter-zpages/src/zpages-frontend/page-handlers/tracez.page-handler.ts
The template expects the span properties to be in the "global" scope.
(postmortem idea: we should start to consider testing on template outputs)
=> fix(exporter-zpages): zpages template scope

packages/opencensus-core/src/trace/model/no-record/no-record-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-span.ts
It is expensive to add object type values to the span now because the user needs to serialize them even if the sampling decision is none. After this change, the `NoRecordSpan` would handle it in a zero cost way.
=> feat(core): support object type attribute on spans

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This is to match other languages templates. Example: https://github.com/census-instrumentation/opencensus-python/tree/master/.github/ISSUE_TEMPLATE
=> Remove "triage me" label from ISSUE_TEMPLATE

packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/exporter-buffer.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/test/test-root-span.ts, packages/opencensus-core/test/test-span.ts, packages/opencensus-exporter-instana/src/instana.ts, packages/opencensus-exporter-jaeger/src/jaeger.ts, packages/opencensus-exporter-ocagent/src/ocagent.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts, packages/opencensus-exporter-zipkin/src/zipkin.ts, packages/opencensus-exporter-zipkin/test/test-zipkin.ts, packages/opencensus-exporter-zpages/src/zpages.ts, packages/opencensus-instrumentation-grpc/test/test-grpc.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts, packages/opencensus-instrumentation-https/test/test-https.ts, packages/opencensus-instrumentation-ioredis/test/test-ioredis.ts, packages/opencensus-instrumentation-mongodb/test/test-mongodb.ts, packages/opencensus-instrumentation-redis/test/test-redis.ts
Today Tracer only reports root spans to exporters.
After this change every span will be reported to exporters, letting exporters filter on what they want to handle.
*Today some exporters (`opencensus-exporter-jaeger`) walk through `rootSpan.spans`, while others (`opencensus-exporter-ocagent`) use `adaptRootSpan()` to flatten spans, while other exporters completely skip child spans.*
This PR doesn't change Jaeger and ocagent exporters behaviour.
Changes:
- report all spans to exporters
- filter to RootSpan only in `opencensus-exporter-jaeger` to match the previous behaviour
- filter to RootSpan only in `opencensus-exporter-ocagent` to match the previous behaviour
- fix Zipkin reporting `shared` property for child spans
- upgrade handlebar to avoid security vulnerability (unrelated change, …
=> fix(tracer): report every span to exporters

package.json
Expose package level fix in lerna.
=> chore(lerna): add fix script

CHANGELOG.md, packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/test/test-metric-registry.ts
Updates #450
Registering Derived Cumulative APIs with **[Metric-Registry](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/metrics/metric-registry.ts)** will be in a follow-up PR. Dependency on #503
=> Plug-in Cumulative APIs into the Metric-Registry

packages/opencensus-core/src/index.ts, packages/opencensus-core/src/metrics/cumulative/derived-cumulative.ts, packages/opencensus-core/src/metrics/types.ts, packages/opencensus-core/src/metrics/utils.ts, packages/opencensus-core/test/test-derived-cumulative.ts
Updates #450 
Specs: https://github.com/census-instrumentation/opencensus-specs/pull/254/files?short_path=0aaf645#diff-0aaf6455b2b0b7a5f2ed45f6b36792ee
This is mostly same as [derived-gauge](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/metrics/gauges/derived-gauge.ts). 
Last piece, registering with **[Metric-Registry](https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/metrics/metric-registry.ts)** will be in a follow-up PR.
=> Add support for Derived Cumulative API

CHANGELOG.md, packages/opencensus-core/src/trace/config/types.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/test/test-tracer-base.ts, packages/opencensus-core/test/test-tracer.ts, packages/opencensus-nodejs/README.md
Default attributes for Tracer that will be added to every Span created by Tracer.
Useful for system level attributes like cluster information.
=> feat(core): start tracer with span attributes

CHANGELOG.md, packages/opencensus-core/src/common/validations.ts, packages/opencensus-core/src/metrics/metric-registry.ts, packages/opencensus-core/test/test-metric-registry.ts
Fixes #450
Completed earlier PRs.
=> Plug-in Derived Cumulative into the Metric-Registry

.circleci/config.yml
Fixes #511.
The follow up PR should be to upgrade engines field to >=8.x.
=> Chore: remove node 6 ci job

CHANGELOG.md, packages/opencensus-core/src/trace/model/no-record/no-record-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/src/trace/model/types.ts
Continuation of #484, this PR is to cleanup and match internal interfaces with top level APIs. i.e. Internal `startChildSpan` interface accepts same argument(`SpanOptions`) as public facing Tracer's  `startChildSpan`.
**This PR does not contain any breaking change.**
=> `startChildSpan` with `SpanOptions` interface only.

packages/opencensus-core/src/stats/types.ts, packages/opencensus-core/src/trace/instrumentation/types.ts
This PR fixes Issue [#527](https://github.com/census-instrumentation/opencensus-node/issues/527).
* Adds a Default function declaration in @opencensus/core stats/types.ts to avoid import of internal functionality.
* As small change, adds missing semicolon.
=> Change CLS import to make stats types more general. (Fix #527)

CONTRIBUTING.md
Adding some information that would have been useful
to me when I was working on my first commit.
=> doc: add some use info to CONTRIBUTING.md

examples/grpc/package.json, examples/http/package.json, examples/stats/exporter/package.json, package.json, packages/opencensus-core/package.json, packages/opencensus-exporter-instana/package.json, packages/opencensus-exporter-jaeger/package.json, packages/opencensus-exporter-ocagent/package.json, packages/opencensus-exporter-prometheus/package.json, packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-exporter-zipkin/package.json, packages/opencensus-exporter-zpages/package.json, packages/opencensus-instrumentation-all/package.json, packages/opencensus-instrumentation-grpc/package.json, packages/opencensus-instrumentation-http/package.json, packages/opencensus-instrumentation-http2/package.json, packages/opencensus-instrumentation-https/package.json, packages/opencensus-instrumentation-ioredis/package.json, packages/opencensus-instrumentation-mongodb/package.json, packages/opencensus-instrumentation-redis/package.json, packages/opencensus-nodejs-base/package.json, packages/opencensus-nodejs/package.json, packages/opencensus-propagation-b3/package.json, packages/opencensus-propagation-binaryformat/package.json, packages/opencensus-propagation-jaeger/package.json, packages/opencensus-propagation-tracecontext/package.json, packages/opencensus-resource-util/package.json
We have already deprecated Node 6 support #511.
=> Chore: upgrade engines field to >=8

packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts
While debugging #526, I found we are not assigning `currentRootSpan` correctly, especially in case of tracer with cls. Ideally, we should set `currentRootSpan` before the `onStartSpan` event. This change is done in https://github.com/census-instrumentation/opencensus-node/commit/92edaa9d406ac74e1805a4e80b756acedc413001#diff-b46c2c01fbf239aae015e19185803e0dL154
The `onStartSpan` and `onEndSpan` events contains following check -> 
```
if (this.currentRootSpan.traceId !== root.traceId) {
this.logger.debug(
'currentRootSpan != root on notifyStart. Need more investigation.');
}
```
=> set CurrentRootSpan correctly

CHANGELOG.md, packages/opencensus-core/src/trace/instrumentation/types.ts, packages/opencensus-instrumentation-http/src/http.ts, packages/opencensus-instrumentation-http/src/types.ts, packages/opencensus-instrumentation-http/test/test-http.ts, packages/opencensus-instrumentation-https/test/test-https.ts
Add support for custom attributes for http and https spans
Fixes: https://github.com/census-instrumentation/opencensus-node/issues/490
I've marked as Work in progress WIP as I've not looked at the updates needed to add any required documentation and to add tests.
I'm away until May 8th so I won't get back to the docs and tests until then but I wanted to get this out so that people could review provide additional feedback.
I think it is in line with the recommendations in https://github.com/census-instrumentation/opencensus-node/issues/490 and it seems to work based on my test app.
=> Add support for custom attributes

packages/opencensus-exporter-prometheus/src/prometheus-stats.ts, packages/opencensus-exporter-prometheus/test/test-prometheus-stats.ts
Currently, the `tags` is a type of map with `TagKey` as Key and `TagValue` as value. We used `Map.prototype.has` function to detect if a key is already defined, if no skip it otherwise get the associated value for it. AFAIK, The maps detects existence ( Map.prototype.has ( key )) of keys based on equality (===). Primitives like strings and numbers are compared by their value, while objects (arrays, plain objects) are compared by their reference. That comparison by reference basically checks to see if the objects given refer to the same location in memory. 
To solve the problem (short-term), I would prefer to create copy of original map with string as the key type. The alternative solution would be to change `tags: Map<TagKey, TagValue>` to `tags: Map<string, TagValue>`. It would require …
=> Exporter/Prometheus: Fix missing tags for HTTP metrics

.circleci/config.yml
~~I am optimistic about tests and build, Let's see how much work required to add support for node 12.
Edit 2: I have updated GRPC package to 1.20.3 to pass the build on Node 12 #535.~~
=> chore: add node 12 ci job

CHANGELOG.md, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring-utils.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts
Fixes #365, Follow-up PR of https://github.com/census-instrumentation/opencensus-node/pull/405.
Stackdriver TimeSeries#Exemplar API: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#Exemplar
=> Exporter/Stackdriver: Support Exemplar in Stackdriver TimeSeries

CHANGELOG.md, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
To fix https://github.com/census-instrumentation/opencensus-node/issues/537
This PR enables us to set the Stackdriver's credentials from the environment variables instead of ADC. c.f. https://cloud.google.com/docs/authentication/production
It's ok to use `GOOGLE_APPLICATION_CREDENTIALS` as before or use the `credentials` option passing to the `StackdriverTraceExporter / StackdriverStatsExporter` constructor.
```ts
import { StackdriverTraceExporter } from "@opencensus/exporter-stackdriver";
// load the environment variable with keys encoded with Base64
const jsonContent = Buffer.from(process.env.CREDENTIALS_BASE64, "base64").toString();
const credentials = JSON.parse(jsonContent);
const exporter = StackdriverTraceExporter({
projectId: "project-id",
credentails: credentials,
});
```
=>  Enable to receive credentials object in creating Stackdriver exporter

packages/opencensus-core/src/exporters/console-exporter.ts, packages/opencensus-core/src/exporters/types.ts, packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts, packages/opencensus-core/src/trace/model/no-record/no-record-span.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-exporter-instana/src/instana.ts, packages/opencensus-exporter-jaeger/src/jaeger.ts, packages/opencensus-exporter-ocagent/src/adapters.ts, packages/opencensus-exporter-ocagent/src/ocagent.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts, packages/opencensus-exporter-zipkin/src/zipkin.ts
=> Fix duplicate spans issue and clean up

packages/opencensus-propagation-tracecontext/src/tracecontext-format.ts, packages/opencensus-propagation-tracecontext/test/test-tracecontext-format.ts
Fixes #546 
This PR contains the following changes:
1. Get rid of superfluous falseness checks in Trace Context Propagation.
2. If there is no trace context in the headers, or if the parsed `TraceId` or `SpanId` is invalid, return null instead of empty `SpanContext` object.
These changes have all been tested locally and been confirmed to be working.
=> Trace Context Propagation: return null instead of empty spancontext

packages/opencensus-exporter-stackdriver/src/common-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-monitoring-utils.ts, packages/opencensus-resource-util/src/constants.ts, packages/opencensus-resource-util/src/index.ts, packages/opencensus-resource-util/src/resource-labels.ts, packages/opencensus-resource-util/src/resource-utils.ts, packages/opencensus-resource-util/test/test-detect-resource.ts
Fixes #454
Specs: census-instrumentation/opencensus-specs#235
=> Refactor resource util to match specs.

packages/opencensus-exporter-object/.npmignore, packages/opencensus-exporter-object/AUTHORS, packages/opencensus-exporter-object/LICENSE, packages/opencensus-exporter-object/README.md, packages/opencensus-exporter-object/codecov.yml, packages/opencensus-exporter-object/package-lock.json, packages/opencensus-exporter-object/package.json, packages/opencensus-exporter-object/src/index.ts, packages/opencensus-exporter-object/src/object.ts, packages/opencensus-exporter-object/test/test-object.ts, packages/opencensus-exporter-object/tsconfig.json
I'm considering to use an in-memory exporter approach for unit testing.
This PR adds an `object-exporter` that stores started, ended and published spans in memory and makes them accessible.
=> Object Trace Exporter for programatic span access

packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/test/test-span.ts
After consolidation of `Span` and `RootSpan`, we set the RootSpan to CurrentRootSpan only when `parentSpanId` is null.
Which is:
```
if (!this.parentSpanId) {
this.tracer.setCurrentRootSpan(this);
}
```
This causes an issue when `parentSpanId` is propagating on wire. In that case, although we create a new `RootSpan` it does not get set to CurrentRootSpan, therefore we create a new root span (instead of child span) for subsequent (outgoing) request.
which is:
```
// Checks if this outgoing request is part of an operation by checking
// if there is a current root span, if so, we create a child span. In
// case there is no root span, this means that the outgoing request is
// the first operation, therefore we create a root span.
if (!plugin.tracer.currentRootSpan) {
// outgoingRequest …
```
=> Fixes #566: set CurrentRootSpan whenever created span is RootSpan

packages/opencensus-exporter-zipkin/src/zipkin.ts, packages/opencensus-exporter-zipkin/test/test-zipkin.ts
0.14.0 unfortunately, breaks nested child support in Zipkin.
- fix support for nested child spans
- test for published spans
Related to:
https://github.com/census-instrumentation/opencensus-node/pull/545/files#diff-427d5fa67f108e0a06e484bd47da9015R81
=> Fix nested child span support for Zipkin

packages/opencensus-nodejs-base/src/trace/instrumentation/plugin-loader.ts
`require-in-the-module` frames pollute CPU Profiles, also performance impact is not clear.
Do not enable when not necessary.
=> feat(nodejs-base): do not hook require when not necessary

CHANGELOG.md, packages/opencensus-core/src/trace/model/no-record/no-record-root-span.ts, packages/opencensus-core/src/trace/model/no-record/no-record-span.ts, packages/opencensus-core/src/trace/model/root-span.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/src/trace/model/tracer-base.ts, packages/opencensus-core/src/trace/model/tracer.ts, packages/opencensus-core/src/trace/model/types.ts, packages/opencensus-core/test/test-no-record-span.ts
Making tracer always available on spans would make it easier to create child spans from existing span instances when you pass your span around.
Further explanation:
https://github.com/open-telemetry/opentelemetry-specification/issues/21
=> feat(span): make tracer available on span

packages/opencensus-core/src/internal/clock.ts, packages/opencensus-core/src/trace/model/span.ts, packages/opencensus-core/test/test-span.ts
`new Date()` is vulnerable to [clock drifts](https://en.wikipedia.org/wiki/Clock_drift). This PR changes child span clocks to start relative to root span by using `process.hrtime`.  Otherwise in-process spans can have an invalid casualty.
=> fix(span): make child span clock relative to root span

packages/opencensus-exporter-zipkin/README.md
The group id of the Zipkin Server maven artifact has changed in recent versions, so the previous instructions would not download the latest version of the server. The quickstart script provided by Zipkin is the recommended way to download the Zipkin Server jar and will download the latest version.
=> Use Zipkin quickstart script in download instructions

.github/CODEOWNERS
Justin Smith is no longer associated with OpenCensus project due to other assignments. Replacing him with Peter Marton (@hekike).
=> Nominating @hekike as a code owner

CHANGELOG.md, packages/opencensus-instrumentation-http2/src/http2.ts, packages/opencensus-instrumentation-http2/test/test-http2.ts
This PR fixes TypeError occurring when `http2.connect` is called with `url.URL`.
It is permitted according to [official document](https://nodejs.org/api/http2.html#http2_http2_connect_authority_options_listener).
A following code reproduces the error.
Source:
```javascript
const tracing = require('@opencensus/nodejs');
const zipkin = require('@opencensus/exporter-zipkin');
const tracer = tracing.start({samplingRate: 1.0}).tracer;
const http2 = require('http2');
tracer.registerSpanEventListener(new zipkin.ZipkinTraceExporter({
url: 'http://localhost:9411/api/v2/spans',
serviceName: 'node.js-open-census-bug'
}));
const url = new URL('/index.html', 'https://example.com/');
const client = http2.connect(url);
const {
HTTP2_HEADER_STATUS
} = http2.constants;
const headers = {};
const req = …
```
=> Fix a TypeError of url.parse

CHANGELOG.md, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace-utils.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace-utils.ts
Resolves #651
These changes have all been tested locally against a real stackdriver instance and been confirmed to be working.
Earlier | Now 
-- | --
=> Map http attributes to the stackdriver format

packages/opencensus-instrumentation-https/src/https.ts, packages/opencensus-instrumentation-https/test/test-https.ts
shameful copy from the http plugin code, to fix the
`https.get` same as `http.get`.
https://github.com/census-instrumentation/opencensus-node/issues/653
Copied from https://github.com/census-instrumentation/opencensus-node/pull/324/files
=> Fix propagation breaking for https.get

packages/opencensus-core/src/common/version.ts
=> fix: core version

packages/opencensus-resource-util/src/resource-utils.ts, packages/opencensus-resource-util/test/test-detect-resource.ts
Resolves #727
These changes have all been tested locally against a real GKE and Stackdriver instance and been confirmed to be working.
=> fix(resources): GKE pod name label

packages/opencensus-core/src/internal/cls-ah.ts
Node.js v12 is affected by a V8 regression where many
insert/deletes on a POJO will trigger an undefined state on V8, leading
to a huge performance regression which can cause each insert/delete
operations on that object to take hundreds of times more. The Map
structure is not affected by this performance regression (and is
recommended by engine developers to deal with large key/value stores).
Contexts on cls-ah are stored on a POJO, and since inserts/deletes
happen often (they are triggered by async_hooks on init and destroy),
applications with high RPS or with high amount of async operations will
hit the threshold, turning the regression on and leading to a huge
performance overhead on each new async operation. Changing to a Map will
avoid that issue.
Ref: …
=> chore(core): store cls contexts on a Map

package-lock.json, packages/opencensus-core/package-lock.json, packages/opencensus-exporter-azure/package-lock.json, packages/opencensus-exporter-instana/package-lock.json, packages/opencensus-exporter-jaeger/package-lock.json, packages/opencensus-exporter-object/package-lock.json, packages/opencensus-exporter-ocagent/package-lock.json, packages/opencensus-exporter-prometheus/package-lock.json, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-zipkin/package-lock.json, packages/opencensus-exporter-zpages/package-lock.json, packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-http/package-lock.json, packages/opencensus-instrumentation-http2/package-lock.json, packages/opencensus-instrumentation-https/package-lock.json, packages/opencensus-instrumentation-ioredis/package-lock.json, packages/opencensus-instrumentation-mongodb/package-lock.json, packages/opencensus-instrumentation-redis/package-lock.json, packages/opencensus-nodejs-base/package-lock.json, packages/opencensus-nodejs/package-lock.json, packages/opencensus-propagation-b3/package-lock.json, packages/opencensus-propagation-binaryformat/package-lock.json, packages/opencensus-propagation-jaeger/package-lock.json, packages/opencensus-propagation-stackdriver/package-lock.json, packages/opencensus-propagation-tracecontext/package-lock.json, packages/opencensus-resource-util/package-lock.json
Some package-lock.json files had were using an npm mirror from netflix that is no longer working. For example https://artifacts.netflix.com/api/npm/npm-netflix/@babel/code-frame/-/code-frame-7.0.0.tgz is broken and it should use registry.npmjs.org. So I ran:
```
perl -i -p -e 's/https:\/\/artifacts\.netflix\.com\/api\/npm\/npm-netflix/https:\/\/registry.npmjs.org/' `git ls-files **/package-lock.json`
```
and then was able to run `npm install` normally and everything completed alright.
=> chore: update broken package-lock resolves

.circleci/config.yml, CHANGELOG.md, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-stackdriver/package.json, packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/test/test-stackdriver-cloudtrace.ts
BREAKING CHANGE: major version upgrade google-auth-library
BREAKING CHANGE: dropping support node8 for security fix
---
Partial fix for #864
- To fix a high vulnerability security problem in google-auth-library, had to upgrade to v6 which only supports node10+.
- Clean/refactor the CircleCI config so that I can pass extra arguments to skip this package on the node8 build
- Also had to upgrade typescript to support this, and make some ts annotation changes for this
- Upgraded package-lock (doesn't effect users) with `npm audit fix`, no longer any security issues.
- `npm run fix` to re-format code with upgrade gts
=> chore(stackdriver): upgrade google-auth-library, drop node8

packages/opencensus-propagation-jaeger/src/jaeger-format.ts, packages/opencensus-propagation-jaeger/src/validators.ts, packages/opencensus-propagation-jaeger/test/test-jaeger-format.ts
jaeger format traceId validator seems to have been copied from the W3C TraceContext format validator as the function comments suggest.
however there is a difference as jaeger also allows shorter (64-bit) traceIds, while W3C doesnt.
this leads to unexpected behavior. e.g. if you start the trace with nginx-ingress, which creates 64-bit traceId. If those are propagated, the subsequent service will fail the validation on injection when doing a http call to yet another service. ultimately, the subsequent services are shown as children of nginx and not as children of the other service.
its working as expected if you bypass nginx and the initial traceId is 128bit length
=> Fix traceid validator

.github/workflows/ci.yaml
This is in preparation for #905, migrating to Github actions. GCP has limited CircleCI quota and automated PRs are consuming a ton of this quota. This will also speed up jobs, based on testing I've done so far.
=> chore: add initial noop github action

.circleci/config.yml, .github/workflows/ci.yaml
Part 2 after #906 
Fixes #891
- Drops CI for Node 11 (which was not a LTS release) adds 14 and 16 which are active. Keeping Node 10 CI for now.
- Should otherwise be the same as existing CircleCI jobs
- Not migrating the CircleCI `publish_npm` job yet. This just migrates CI jobs.
=> chore: use github actions for CI runs

renovate.json
`renovate.json` had a bunch of old and no longer recognized config options. This upgrades it to be similar to this renovate config in Google's OTel repo https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/main/renovate.json
=> chore: update renovate config to be less noisy

.github/workflows/ci.yaml, packages/opencensus-core/package-lock.json, packages/opencensus-exporter-azure/package-lock.json, packages/opencensus-exporter-instana/package-lock.json, packages/opencensus-exporter-jaeger/package-lock.json, packages/opencensus-exporter-object/package-lock.json, packages/opencensus-exporter-ocagent/package-lock.json, packages/opencensus-exporter-prometheus/package-lock.json, packages/opencensus-exporter-stackdriver/package-lock.json, packages/opencensus-exporter-zipkin/package-lock.json, packages/opencensus-exporter-zpages/package-lock.json, packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-http/package-lock.json, packages/opencensus-instrumentation-http2/package-lock.json, packages/opencensus-instrumentation-https/package-lock.json, packages/opencensus-instrumentation-ioredis/package-lock.json, packages/opencensus-instrumentation-mongodb/package-lock.json, packages/opencensus-instrumentation-redis/package-lock.json, packages/opencensus-nodejs-base/package-lock.json, packages/opencensus-nodejs/package-lock.json, packages/opencensus-propagation-b3/package-lock.json, packages/opencensus-propagation-binaryformat/package-lock.json, packages/opencensus-propagation-jaeger/package-lock.json, packages/opencensus-propagation-stackdriver/package-lock.json, packages/opencensus-propagation-tracecontext/package-lock.json, packages/opencensus-resource-util/package-lock.json, packages/opencensus-resource-util/package.json, packages/opencensus-resource-util/test/test-detect-resource.ts
- BREAKING CHANGE: drops support for node 8 in `@opencensus/resource-util` package. This is OK because the only dependent is the stackdriver exporter which already dropped it.
- Fixed tests to pass with the new behavior
Fixes #808
=> chore: upgrade gcp-metadata to 4.x

renovate.json
Take two of #912. This time I tested it on my fork, which appears to be correctly grouping dependencies: https://github.com/aabmass/opencensus-node/pull/5
- Removed the schedule, because its not too important
- Added `dependencyDashboard` which will create an issue with overview of all dependency PRs
=> chore: update renovate config - take 2

packages/opencensus-exporter-azure/package-lock.json, packages/opencensus-exporter-instana/package-lock.json, packages/opencensus-exporter-jaeger/package-lock.json, packages/opencensus-exporter-object/package-lock.json, packages/opencensus-exporter-ocagent/package-lock.json, packages/opencensus-exporter-zipkin/package-lock.json, packages/opencensus-instrumentation-all/package-lock.json, packages/opencensus-instrumentation-grpc/package-lock.json, packages/opencensus-instrumentation-http/package-lock.json, packages/opencensus-instrumentation-https/package-lock.json, packages/opencensus-instrumentation-ioredis/package-lock.json, packages/opencensus-instrumentation-redis/package-lock.json, packages/opencensus-nodejs-base/package-lock.json, packages/opencensus-nodejs/package-lock.json, packages/opencensus-propagation-b3/package-lock.json, packages/opencensus-propagation-binaryformat/package-lock.json, packages/opencensus-propagation-jaeger/package-lock.json, packages/opencensus-propagation-stackdriver/package-lock.json, packages/opencensus-propagation-tracecontext/package-lock.json, packages/opencensus-resource-util/package-lock.json
This upgrades all package-lock files that have locked production vulnerabilities. This doesn't actually effect users at all (package-lock files are not shipped) but removes vulnerabilities in CI pipeliens
=> chore: ran npm audit fix --production in subpackages

.github/workflows/ci.yaml
Skipping modules marked private in package.json. These are mostly examples which rely on stackdriver exporter, which doesn't support node8 anymore.
=> chore: skip private modules in node8

packages/opencensus-exporter-stackdriver/src/stackdriver-cloudtrace.ts, packages/opencensus-exporter-stackdriver/src/stackdriver-monitoring.ts, packages/opencensus-exporter-stackdriver/src/types.ts
This is useful if you want to use non-standard endpoints (e.g. staging or upcoming regional APIs).
=> Allow specifying apiEndpoint for stackdriver exporters
